import { useCallback,useEffect,useState } from 'react'
import { AlertTriangle,Ban,Bot,Check,Clock3,KeyRound,RefreshCw,ShieldAlert } from 'lucide-react'
import { fetchMt5State,type LiveState } from './lib/mt5'
import { MarketChart } from './MarketChart'

const clock=(value:string)=>new Intl.DateTimeFormat('es-MX',{timeZone:'America/Mexico_City',dateStyle:'short',timeStyle:'medium'}).format(new Date(value))
const price=(value:number|null)=>value===null?'—':new Intl.NumberFormat('en-US',{maximumFractionDigits:2}).format(value)

export function Autopilot(){
  const [token,setToken]=useState(()=>localStorage.getItem('tradinglab:read-token')??'')
  const [draft,setDraft]=useState(''),[state,setState]=useState<LiveState|null>(null),[loading,setLoading]=useState(false),[error,setError]=useState(''),[now,setNow]=useState(Date.now())
  const refresh=useCallback(async(signal?:AbortSignal)=>{if(!token)return;setLoading(true);try{setState(await fetchMt5State(token,signal));setError('')}catch(reason){if(!signal?.aborted)setError(reason instanceof Error?reason.message:'No se pudo consultar el piloto.')}finally{if(!signal?.aborted)setLoading(false)}},[token])
  useEffect(()=>{const controller=new AbortController();refresh(controller.signal);const timer=window.setInterval(()=>{setNow(Date.now());refresh(controller.signal)},10_000);return()=>{controller.abort();window.clearInterval(timer)}},[refresh])
  const latest=state?.decisions?.[0],connected=state?.account&&now-new Date(state.account.snapshot_at).getTime()<90_000
  const decisionFresh=latest&&now-new Date(latest.evaluated_at).getTime()<7*60_000
  const parts=new Intl.DateTimeFormat('en-US',{timeZone:'America/Mexico_City',hour:'2-digit',minute:'2-digit',hour12:false}).formatToParts(new Date(now)),hour=Number(parts.find(p=>p.type==='hour')?.value??0),minute=Number(parts.find(p=>p.type==='minute')?.value??0),total=hour*60+minute,sessionState=total>=300&&total<630?'entries':total>=630&&total<660?'management':'closed'
  if(!token)return <section className="page"><div className="page-title"><div><span className="eyebrow">ACCESO PROTEGIDO</span><h1>Piloto automático.</h1><p>Utiliza el mismo token de lectura de Cuenta MT5.</p></div></div><article className="panel token-panel"><KeyRound/><h2>Token de lectura</h2><label className="field"><span>Token</span><div><input type="password" value={draft} onChange={e=>setDraft(e.target.value)} autoComplete="off"/></div></label><button className="primary wide" onClick={()=>{const value=draft.trim();localStorage.setItem('tradinglab:read-token',value);setToken(value)}}>Conectar navegador</button></article></section>
  return <section className="page autopilot-page"><div className="page-title"><div><span className="eyebrow">BTCUSD · ÚLTIMO MODO REPORTADO: {latest?.mode==='demo'?'DEMO':'SOMBRA'}</span><h1>Decisiones automáticas, capital protegido.</h1><p>Observa señales, bloqueos y ejecución confirmada en MT5; el modo mostrado puede estar atrasado.</p></div><div className={`status-badge ${connected&&decisionFresh?'approved':'blocked'}`}>{connected&&decisionFresh?<Check/>:<AlertTriangle/>}{connected&&decisionFresh?'Sync y Trader recientes':'Sin confirmación reciente de ambos EA'}</div></div>
    {error&&<div className="notice error"><AlertTriangle/>{error}<button onClick={()=>{localStorage.removeItem('tradinglab:read-token');setToken('')}}>Cambiar token</button></div>}
    <div className="autopilot-status-grid"><article className="panel autopilot-mode"><span className="eyebrow">ESTADO REPORTADO</span><div><Bot/><strong>{latest?.mode==='demo'?'Demo':'Sombra'}</strong></div><p>{latest?.mode==='demo'?'Confirma órdenes ejecutadas en Historial de MT5; no basta una señal.':'Analiza y registra; no envía órdenes.'}</p></article><article className="panel"><span className="eyebrow">VENTANA DE ENTRADAS</span><h2><Clock3/> 05:00–10:30</h2><p>Hora de Ciudad de México · BTCUSD</p></article><article className="panel"><span className="eyebrow">GESTIÓN ÚNICAMENTE</span><h2>10:30–11:00</h2><p>Sin entradas nuevas; una posición protegida puede continuar.</p></article><article className="panel"><span className="eyebrow">FUERA DE SESIÓN</span><h2><Ban/> 11:00–05:00</h2><p>Sin entradas. Las posiciones conservan SL y TP.</p></article></div>
    <article className="panel safety-lock"><ShieldAlert/><div><span className="eyebrow">BLOQUEO DE CAPITAL REAL</span><h2>El EA sólo admite ejecución en demo autorizada</h2><p>La web no puede confirmar los interruptores locales: verifícalos en MT5. Sin registro reciente no se deben interpretar señales como actuales.</p></div><span className={`session-chip ${sessionState}`}>{sessionState==='entries'?'Buscando configuraciones':sessionState==='management'?'Sólo gestión':'Sesión cerrada'}</span></article>
    <div className="autopilot-grid"><article className="panel latest-decision"><div className="panel-head"><div><span className="eyebrow">ÚLTIMA EVALUACIÓN M5</span><h2>{latest?latest.symbol:'Esperando al EA de estrategia'}</h2></div><button className="icon-button refresh" onClick={()=>refresh()} aria-label="Actualizar"><RefreshCw className={loading?'spin':''}/></button></div>{latest?<><div className={`decision-verdict ${latest.verdict}`}><strong>{labelVerdict(latest.verdict)}</strong><span>{latest.reason}</span></div><div className="decision-levels"><span>Dirección <b>{latest.side?latest.side==='buy'?'COMPRA':'VENTA':'—'}</b></span><span>Entrada <b>{price(latest.entry_price)}</b></span><span>SL <b>{price(latest.stop_loss)}</b></span><span>TP <b>{price(latest.take_profit)}</b></span><span>Ratio <b>{latest.reward_risk?`${latest.reward_risk.toFixed(2)}R`:'—'}</b></span><span>Evaluada <b>{clock(latest.evaluated_at)}</b></span></div></>:<p className="empty-row">Instala TradingLabTrader en un solo gráfico de BTCUSD para comenzar el registro.</p>}</article>
      <article className="panel rules-card"><span className="eyebrow">POLÍTICA ACTIVA</span><h2>Límites no negociables</h2>{[['Riesgo por entrada','0.25%'],['Posiciones simultáneas','1'],['Objetivo inicial','2R'],['Promediar pérdidas','Prohibido'],['Pérdida diaria','−1%'],['Pérdidas consecutivas','3']].map(([label,value])=><div key={label}><span>{label}</span><b>{value}</b></div>)}</article></div>
    <MarketChart token={token} decisions={state?.decisions??[]}/>
    <article className="panel decision-history"><div className="panel-head"><div><span className="eyebrow">TRAZABILIDAD</span><h2>Historial de decisiones</h2></div><small>{state?.decisions?.length??0} evaluaciones recibidas</small></div><div className="decision-table"><div className="decision-row heading"><span>Hora CDMX</span><span>Resultado</span><span>Dirección</span><span>Precios</span><span>Motivo</span></div>{state?.decisions?.map(item=><div className="decision-row" key={item.id}><time>{clock(item.evaluated_at)}</time><b className={`verdict-text ${item.verdict}`}>{labelVerdict(item.verdict)}</b><span>{item.side?item.side==='buy'?'Compra':'Venta':'—'}</span><span>{price(item.entry_price)} / {price(item.stop_loss)} / {price(item.take_profit)}</span><p>{item.reason}</p></div>)}{!state?.decisions?.length&&<p className="empty-row">Aún no existen evaluaciones. El EA registrará una por cada vela M5 cerrada.</p>}</div></article>
  </section>
}

function labelVerdict(value:string){return({outside_session:'Fuera de sesión',blocked:'Bloqueada',no_setup:'Sin configuración',signal:'Señal sombra',order_sent:'Orden demo',error:'Error'} as Record<string,string>)[value]??value}
